# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details

version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci:clojure:lein-2.9.1
  environment:
    LEIN_ROOT: "true"
    JVM_OPTS: -Xmx3200m

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein test
  lint:
    <<: *defaults
    steps:
      - run: lein lint
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint
